### ISSUE TITLE
bug: owner's books appear in books available to borrow

### ISSUE THREAD

**Issue by jscottgray** [CMPUT301W19T03/iShelf#127]
books available to borrow should filter out the owner's books. When I go to a book I own through the all books tab, it doesn't allow me to see requests

**Comment by mehrabmehdi** [comment]
what do you mean by the 2nd one? it works fine for me.

**Comment by mehrabmehdi** [comment]
but yeah owned books need to be filtered out from the borrow book fragment

**Comment by mehrabmehdi** [comment]
i'll make that fix
