### ISSUE TITLE
bug: viewing book profile doesn't accurately reflect current state

### ISSUE THREAD

**Issue by jscottgray** [CMPUT301W19T03/iShelf#128]
if i have borrowed a book, i can still request it? Shouldn't be able to

**Comment by jscottgray** [comment]
can't see current requests if i click on the request in the request tab

**Comment by rmnattas** [comment]
I thought I fixed that in #120

**Comment by mehrabmehdi** [comment]
does it still show that you can make a request after you borrowed a book?
